### ISSUE TITLE
PSS tally in multithread mode

### ISSUE THREAD

**Issue by cvalcort** [PenRed/PenRed#60]
I tried the PSS tally using the last PenRed version (up today) in a multithreaded mode (4 threads), and the PSS tallies (primary, scattered, and multi-scattered) get calculated only by one thread (penred compiled with the option -DWITH_MULTI_THREADING="ON" :). I noticed this because the sum of all threads doesn't add up with the total dose, and the trend is like this 
1 thread : total dos = sum
2 thread: total dose = 2 sum
4 threads: total dose = 4 sum

I got rid of this problem by commenting the following lines in the ~/path-to-PenRed/src/tallies/generic/tallyPSS.cpp file and recompiling:

//Set thread
//   primary->setThread(getThread());
//   scatter->setThread(getThread());
//   multiScatter->setThread(getThread());

After this modification the results agree using threads in a single PC. Then, I proved these modifications in an MPI environment (300 processes), but without using threads (sad), and the thing ran just fine. I don't know if what I did messes with something else in the code.

**Comment by vigial** [comment]
Thank you for your report. It appears that the configuration is not properly shared from thread 0 to the other threads when using the PSS tally. Since the default thread number is 0, not assigning any specific thread forces all threads to complete the entire configuration, ensuring the simulation runs correctly.

The commit 4e00716dd865c047b90548adbc8e5460469c4f34 should address this issue. Could you please download the branch v-1.11.0 and test it?

If the problem persists, please provide an example to reproduce the issue, as it seems to affect only the tallies using configuration sharing.

**Comment by cvalcort** [comment]
Now the PSS tally works fine. Thanks!!

**Comment by vigial** [comment]
Perfect! The branch with the fix has been merged into the master branch
